# Generated by Django 5.2 on 2025-04-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('tipo_sangue', models.CharField(max_length=4)),
                ('sintomas', models.TextField(max_length=200)),
            ],
        ),
    ]
