# Generated by Django 5.2 on 2025-04-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
